from machine import I2C, Pin
from bmp280 import *


#Code automatically generated by BIPES (http://www.bipes.net.br)
#Author: 'User'
#IOT ID: 0
#Description: 'My project'

bus=I2C(scl=Pin(22), sda=Pin(21))
bmp280 = BMP280(bus)
bmp280.use_case(BMP280_CASE_WEATHER)
bmp280.oversample(BMP280_OS_HIGH)
for count in range(10):
  bmp280.normal_measure()
  print('pressao ' + str(bmp280.pressure))
