from machine import I2C, Pin
import time

def sht20_temperature():
	i2c.writeto(0x40,b'\xf3')
	time.sleep_ms(70)
	t=i2c.readfrom(0x40, 2)
	return -46.86+175.72*(t[0]*256+t[1])/65535

def sht20_humidity():
	i2c.writeto(0x40,b'\xf5')
	time.sleep_ms(70)
	t=i2c.readfrom(0x40, 2)
	return -6+125*(t[0]*256+t[1])/65535


#Code automatically generated by BIPES (http://www.bipes.net.br)
#Author: 'User'
#IOT ID: 0
#Description: 'My project'
i2c=I2C(scl=Pin(22), sda=Pin(21))
for count in range(10):
  print('temperatura     ' + str(sht20_temperature()))
  print('Humidade     ' + str(sht20_humidity()))
